-- 表结构备份 2026-05-03 22:44:26
-- 表名: orders

CREATE TABLE `orders` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_no` varchar(50) NOT NULL,
  `customer_name` varchar(100) NOT NULL,
  `customer_phone` varchar(20) DEFAULT NULL,
  `customer_address` varchar(255) DEFAULT NULL,
  `customer_group` varchar(50) DEFAULT NULL,
  `product_type` varchar(50) NOT NULL,
  `material` varchar(50) DEFAULT '',
  `mesh_size` decimal(10,2) DEFAULT NULL,
  `wire_diameter` decimal(10,2) DEFAULT NULL,
  `width` decimal(10,2) DEFAULT NULL,
  `length` decimal(10,2) DEFAULT NULL,
  `quantity` int DEFAULT '1',
  `unit` varchar(10) DEFAULT '米',
  `unit_price` decimal(10,2) DEFAULT '0.00',
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `surface_treatment` varchar(50) DEFAULT NULL,
  `special_requirements` text,
  `delivery_date` datetime DEFAULT NULL,
  `status` varchar(20) DEFAULT '待确认',
  `remark` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `extra_params` text,
  `customer_id` int DEFAULT NULL COMMENT '客户ID',
  `salesperson` varchar(50) DEFAULT NULL COMMENT '业务员',
  `contact_person` varchar(50) DEFAULT NULL COMMENT '联系人',
  `priority_level` varchar(10) DEFAULT '中' COMMENT '优先级：高/中/低',
  `cancel_reason` text COMMENT '取消原因',
  `order_source` varchar(20) DEFAULT '线下' COMMENT '订单来源',
  `payment_method` varchar(20) DEFAULT NULL COMMENT '付款方式',
  `invoice_type` varchar(30) DEFAULT NULL COMMENT '发票类型',
  `invoice_status` varchar(20) DEFAULT '未开票' COMMENT '发票状态',
  `invoice_no` varchar(50) DEFAULT NULL COMMENT '发票号码',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '软删除标记',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted_by` varchar(50) DEFAULT NULL COMMENT '删除人',
  `created_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(50) DEFAULT NULL COMMENT '最后更新人',
  `version` int DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no` (`order_no`),
  UNIQUE KEY `idx_orders_order_no` (`order_no`),
  KEY `idx_customer_name` (`customer_name`),
  KEY `idx_product_type` (`product_type`),
  KEY `idx_delivery_date` (`delivery_date`),
  KEY `idx_salesperson` (`salesperson`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
