-- 表结构备份 2026-05-03 22:46:26
-- 表名: process_records

CREATE TABLE `process_records` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `production_id` int DEFAULT NULL,
  `process_name` varchar(50) NOT NULL,
  `process_seq` int DEFAULT '1',
  `planned_qty` int DEFAULT NULL,
  `completed_qty` int DEFAULT '0',
  `qualified_qty` int DEFAULT '0',
  `worker` varchar(50) DEFAULT NULL,
  `work_hours` decimal(10,2) DEFAULT '0.00',
  `status` varchar(20) DEFAULT '待开始',
  `remark` text,
  `record_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `is_outsource` tinyint(1) DEFAULT '0',
  `outsource_remark` text,
  `material_usage` decimal(12,2) DEFAULT '0.00',
  `material_unit` varchar(20) DEFAULT 'kg',
  `planned_start` datetime DEFAULT NULL COMMENT '计划开始时间',
  `planned_end` datetime DEFAULT NULL COMMENT '计划结束时间',
  `actual_pause_minutes` int DEFAULT '0' COMMENT '暂停总时长(分钟)',
  `pause_count` int DEFAULT '0' COMMENT '暂停次数',
  `rework_qty` int DEFAULT '0' COMMENT '返工数量',
  `scrap_qty` int DEFAULT '0' COMMENT '报废数量',
  `efficiency` decimal(5,2) DEFAULT NULL COMMENT '效率百分比',
  `machine_no` varchar(30) DEFAULT NULL COMMENT '机台编号',
  `batch_no` varchar(50) DEFAULT NULL COMMENT '生产批次号',
  `shift` varchar(20) DEFAULT NULL COMMENT '班次：早/中/晚',
  `standard_minutes` int DEFAULT NULL COMMENT '标准工时(分钟)',
  `created_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '软删除标记',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted_by` varchar(50) DEFAULT NULL COMMENT '删除人',
  `calculated_qty` decimal(10,4) DEFAULT NULL COMMENT '计算用料量',
  `actual_used_qty` decimal(10,4) DEFAULT NULL COMMENT '实际使用量',
  `waste_rate` decimal(5,2) DEFAULT NULL COMMENT '废品率(%)',
  `setup_time` decimal(5,2) DEFAULT NULL COMMENT '准备时间(小时)',
  `defect_types` text COMMENT '缺陷类型记录',
  `rework_count` int DEFAULT '0' COMMENT '返工次数',
  `start_date` date DEFAULT NULL COMMENT '开始日期',
  `end_date` date DEFAULT NULL COMMENT '结束日期',
  `duration_days` int DEFAULT NULL COMMENT '工序用时(自然天数)',
  PRIMARY KEY (`id`),
  KEY `order_id` (`order_id`),
  KEY `production_id` (`production_id`),
  KEY `idx_batch_no` (`batch_no`),
  KEY `idx_machine_no` (`machine_no`),
  CONSTRAINT `process_records_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  CONSTRAINT `process_records_ibfk_2` FOREIGN KEY (`production_id`) REFERENCES `production_orders` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
