"""8008 同步死信分析"""
import pymysql
CONN_KW = dict(host='127.0.0.1', port=3306, user='root', password='88888888', connect_timeout=5, cursorclass=pymysql.cursors.DictCursor)

print("=" * 60)
print("【A】container_center.sync_log 表结构")
print("=" * 60)
conn = pymysql.connect(database='container_center', **CONN_KW)
cur = conn.cursor()
cur.execute('DESCRIBE sync_log')
for r in cur.fetchall(): print(f"  {r['Field']:25s} {r['Type']}")
print()
print("【B】sync_log 最近 5 条失败")
cur.execute("SELECT * FROM sync_log WHERE status='failed' ORDER BY id DESC LIMIT 5")
for r in cur.fetchall(): print(' ', r)
print()
print("【C】etl_dead_letter 结构")
cur.execute('DESCRIBE etl_dead_letter')
for r in cur.fetchall(): print(f"  {r['Field']:25s} {r['Type']}")
print()
print("【D】etl_dead_letter 最近 5 条")
cur.execute('SELECT * FROM etl_dead_letter ORDER BY id DESC LIMIT 5')
for r in cur.fetchall(): print(' ', r)
print()
print("【E】sync_logs 状态分布")
cur.execute('SELECT status, COUNT(*) c FROM sync_logs GROUP BY status')
for r in cur.fetchall(): print(f"  {r['status']:20s} {r['c']}")
print()
print("【F】最近 sync_logs 5 条")
cur.execute('SELECT * FROM sync_logs ORDER BY id DESC LIMIT 5')
for r in cur.fetchall(): print(' ', r)
conn.close()
