"""共享接口定义"""
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DatabaseConnection(Protocol):
    def cursor(self): ...
    def commit(self): ...
    def rollback(self): ...
    def close(self): ...


@runtime_checkable
class EventPublisher(Protocol):
    def publish(self, event: str, data: dict) -> None: ...
    def subscribe(self, event: str, handler) -> None: ...
